config/routes.rb
Rails.application.routes.draw do

  resources :locations do
  resources :events
end 
  
root 'locations#index'

end

app/models/event.rb
class Event < ActiveRecord::Base 
	belongs_to :location
end 

app/models/location.rb
class Location < ActiveRecord::Base

	has_many :events

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index 
  	@events = Event.all 
  end 



  def new
    @location = Location.find(params[:location_id])
  	@event = Event.new
  end


  def create
      @event = Event.new(event_params)
      @event.location_id = params[:location_id]
      if @event.save
        redirect_to locations_path notice: 'Event was successfully created.'       
      else
        render :new
      end
  end


  def show
  	@event = Event.find(params[:id])
  	@location = @event.location
  end

  def update
    if @event.update(event_params)
        redirect_to locations_path, notice: 'Event was successfully updated.'
      else
        render :edit 
      end
  end

  def edit
  	@event =Event.find(params[:id])
  end
end

def destroy
      @event = Event.find(params[:id])
      @event.destroy
      redirect_to locations_path, notice: 'Event was successfully deleted.'
    end



private
    def event_params
      params.require(:event).permit(:description, :date, :requires_id)
    end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  
  def index
  	@locations = Location.all
  end

  def new
  	@location = Location.new
  end

  def create
      @location = Location.new(location_params)
      if @location.save
          redirect_to locations_path, notice: 'Location was successfully created.' 
      else
       render :new 
      end
  end

    def update
      @location = Location.find(params[:id])
    if @location.update(location_params)
        redirect_to locations_path, notice: 'Event was successfully updated.'
      else
        render :edit 
      end
  end



  def show
  	@location = Location.find(params[:id])
  end

  def edit
  	@location = Location.find(params[:id])
  end

def destroy
      @location = Location.find(params[:id])
      @location.destroy
      redirect_to locations_path, notice: 'Event was successfully deleted.'
    end

private
    def location_params
      params.require(:location).permit(:name, :address, :zipcode)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/new.html.erb
<div class"page-header">
	<h1> New Event </h1> 
</div> 

<%= form_for([@location, @event], html: {class:"form-horizontal"}) do |f| %>

<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :description %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :description, class: "form-control"%>
    </div>
  </div>
</div>


<div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :date %>
    </div>
    <div class="col-md-4">
      <%= f.date_field :date, class: "form-control"%>
    </div>
  </div>


<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    <div class="action">
      <%= f.submit class: "btn btn-primary btn-md active" %>
      <%= link_to 'cancel', locations_path, class: "btn btn-default" %>
      
    </div>
  </div>
</div>

<% end %>

app/views/events/show.html.erb
<p>events show page for cities</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>gCamp</title>
  <%= favicon_link_tag 'favicon.ico' %>

  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>


<body>

 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">JOHN WEEK 5</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>





  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
 
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->


  <div class="container">

    <% if notice %>
    <div class="alert alert-success">
    <center><%= notice %></center>
  </div>


  <% elsif alert %>
  <div class="alert alert-danger"><%= alert %>
  </div>
  <% end %>




    <%= yield %>


    <footer>

      <div class="row">
        <div class="col-md-6">
    
        


        </div>

        <div class="col-md-6 text-right">
          <a href="https://www.linkedin.com/in/johnrmarty/">
         
            <!-- <img alt="Linked in" class="img-footer" src="/app/assets/images/footer/linked_in-f852478f8950eb3fca3367cb545aaa52.png"> -->
          </a>
          <a href="https://github.com/johnrmarty">
      
          </a>
          <a href="https://twitter.com/johnrmarty">
           
          </a>
          <a href="https://students.gschool.it/students/222">
         
          </a>
        </div>




      </footer>
    </div>
  </div> <!-- /container -->

</body>
</html>

app/views/locations/edit.html.erb
<div class= "page-header">
    <h1> Edit Location </h1>
  </div>


<%= form_for(@location, html: {class:"form-horizontal"}) do |f| %>



<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :name %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control"%>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :address %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :address, class: "form-control"%>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :zipcode %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :zipcode, class: "form-control"%>
    </div>
  </div>
</div>


<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    <div class="action">
      <%= f.submit class: "btn btn-primary btn-md active" %>
      <%= link_to 'Cancel', locations_path, class: "btn btn-default" %>



      <% end %>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<div class="page-header">
	<div class="pull-right">
		<%= link_to 'New Location', locations_path, class: "btn btn-primary"%>
	</div>
	<h1>Locations</h1>
</div> 

<table class="table table-striped">
	<tr>
		<th>Name</th>
		<th>Address</th>
		<th>Zipcode</th>
		<th> </th>
		<th> </th>
		<th> </th>
	</tr>
		

	<tbody>
		<% @locations.each do |location| %> 
	<tr>
		<td><%= link_to location.name, location_path(location)  %> </td> 
		<td><%= location.address %></td>
		<td><%= location.zipcode %></td>
				
			<td>
          	<%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-danger" %> 
          	</td>
			<td>
			<%= link_to 'Edit', edit_location_path(location), class: "btn btn-info"%>
			</td>
			<td>
			<%= link_to 'Create Event', new_location_event_path(location), class: "btn btn-info"%>
			</td>
			</div>
	</tr>
			<% end %> 

			</tbody>



</table>

app/views/locations/new.html.erb
<div class"page-header">
	<h1> New Location </h1> 
</div> 

<%= form_for(@location, html: {class:"form-horizontal"}) do |f| %>

<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :name %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control"%>
    </div>
  </div>
</div>


<div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :address %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :address, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :zipcode %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :zipcode, class: "form-control"%>
      </div>
    </div>


<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    <div class="action">
      <%= f.submit class: "btn btn-primary btn-md active" %>
      <%= link_to 'cancel', locations_path, class: "btn btn-default" %>
      
    </div>
  </div>
</div>

<% end %>

app/views/locations/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New Location', new_location_path, class: "btn btn-primary"%>
  </div>
  <h1><%= @location.name %></h1>
</div> 

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Event Address</th>
      <th>Event Zipcode</th>
      <th> </th>
      <th> </th>
      <th> </th>
    </tr>
  </thead>
    
  <tbody>
    <% @location.events.each do |event| %> 
  <tr>
    <td><%= link_to event.description, location_event_path(@location, event)  %> </td> 
    <td><%= event.date %></td>
    <td><%= event.requires_id %></td>
        
      <td>
      <%= link_to 'Delete', location_event_path(@location, event), method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-danger" %> 
      </td>
      <td>
      <%= link_to 'Edit', edit_location_event_path(@location, event), class: "btn btn-info"%>
      </td>
      <td>
      <%= link_to 'Create Event', new_location_event_path(@location), class: "btn btn-info"%>
      </td>

  </tr>
      <% end %> 

      </tbody>



</table>